version: "2"

services:
  api:
    image: codiceplastico-on.azurecr.io/wpc2016/api:v1
    ports:
    - "80:3000"

  worker:
    image: codiceplastico-on.azurecr.io/wpc2016/worker:v1
    
  broker:
    image: rabbitmq:management
    ports:
    - "15672:15672"

  database:
    image: mongo:latest
    