version: "2"

services:
  api:
    build: api
    ports:
    - "80:3000"

  worker:
    build: worker

  broker:
    image: rabbitmq:management
    ports:
    - "15672:15672"

  database:
    image: mongo
    